/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as MechanicsRouteImport } from './routes/mechanics'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as CalculatorRouteImport } from './routes/calculator'

const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const MechanicsRoute = MechanicsRouteImport.update({
  id: '/mechanics',
  path: '/mechanics',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/calculator': typeof CalculatorRoute
  '/calendar': typeof CalendarRoute
  '/clients': typeof ClientsRoute
  '/mechanics': typeof MechanicsRoute
  '/schedule': typeof ScheduleRoute
}
export interface FileRoutesByTo {
  '/calculator': typeof CalculatorRoute
  '/calendar': typeof CalendarRoute
  '/clients': typeof ClientsRoute
  '/mechanics': typeof MechanicsRoute
  '/schedule': typeof ScheduleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/calculator': typeof CalculatorRoute
  '/calendar': typeof CalendarRoute
  '/clients': typeof ClientsRoute
  '/mechanics': typeof MechanicsRoute
  '/schedule': typeof ScheduleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/calculator'
    | '/calendar'
    | '/clients'
    | '/mechanics'
    | '/schedule'
  fileRoutesByTo: FileRoutesByTo
  to: '/calculator' | '/calendar' | '/clients' | '/mechanics' | '/schedule'
  id:
    | '__root__'
    | '/calculator'
    | '/calendar'
    | '/clients'
    | '/mechanics'
    | '/schedule'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  CalculatorRoute: typeof CalculatorRoute
  CalendarRoute: typeof CalendarRoute
  ClientsRoute: typeof ClientsRoute
  MechanicsRoute: typeof MechanicsRoute
  ScheduleRoute: typeof ScheduleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mechanics': {
      id: '/mechanics'
      path: '/mechanics'
      fullPath: '/mechanics'
      preLoaderRoute: typeof MechanicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  CalculatorRoute: CalculatorRoute,
  CalendarRoute: CalendarRoute,
  ClientsRoute: ClientsRoute,
  MechanicsRoute: MechanicsRoute,
  ScheduleRoute: ScheduleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
